# Generated by Django 3.1.3 on 2020-11-23 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbrev', models.CharField(max_length=2)),
                ('state_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=9)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('customer_orders', models.ManyToManyField(to='inventory.Orders')),
                ('state_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.states')),
            ],
        ),
    ]
